# Generated by Django 4.1.7 on 2023-06-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('dob', models.IntegerField()),
                ('gender', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('department', models.TextField()),
                ('course', models.TextField()),
            ],
        ),
    ]
